name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install -o -q --no-dev

      - name: Create Premium Asset
        run: >
          cd ${{ github.workspace }}/../ &&
          zip -r ${{ github.event.repository.name }}/${{ github.event.repository.name }}-premium.zip ${{ github.event.repository.name }}
          -x "${{ github.event.repository.name }}/.git/*"
          -x "${{ github.event.repository.name }}/.github/*"
          "${{ github.event.repository.name }}/phpcs.xml"
          "${{ github.event.repository.name }}/css/src/*"
          "${{ github.event.repository.name }}/js/src/*"
          "${{ github.event.repository.name }}/scripts/*"
          "${{ github.event.repository.name }}/node_modules/*"
          "${{ github.event.repository.name }}/package.json"
          "${{ github.event.repository.name }}/package-lock.json"
          "${{ github.event.repository.name }}/Gulpfile.js"
          "${{ github.event.repository.name }}/composer.json"
          "${{ github.event.repository.name }}/composer.lock"
          "${{ github.event.repository.name }}/.gitignore"
          "${{ github.event.repository.name }}/premia.php"
        
      - name: Remove premium files
        run: rm -rf ${{ github.event.repository.name }}/premium/*

      - name: Prepare Premia Free
        run: |
          composer dump-autoload

      - name: Create Free asset
        run: >
          cd ${{ github.workspace }}/../ &&
          zip -r ${{ github.event.repository.name }}/${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}
          -x "${{ github.event.repository.name }}/.git/*"
          -x "${{ github.event.repository.name }}/.github/*"
          "${{ github.event.repository.name }}/phpcs.xml"
          "${{ github.event.repository.name }}/css/src/*"
          "${{ github.event.repository.name }}/js/src/*"
          "${{ github.event.repository.name }}/scripts/*"
          "${{ github.event.repository.name }}/node_modules/*"
          "${{ github.event.repository.name }}/premium/*"
          "${{ github.event.repository.name }}/package.json"
          "${{ github.event.repository.name }}/package-lock.json"
          "${{ github.event.repository.name }}/Gulpfile.js"
          "${{ github.event.repository.name }}/composer.json"
          "${{ github.event.repository.name }}/composer.lock"
          "${{ github.event.repository.name }}/.gitignore"
          "${{ github.event.repository.name }}/premia-premium.php"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.event.repository.name }}.zip
            ${{ github.event.repository.name }}-premium.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
